### ISSUE TITLE
Incompatibility with the newest tree-sitter

### ISSUE THREAD

**Issue by char0n** [ikatyang/tree-sitter-yaml#18]
Latest 3.0.1 version seems to be incompatible with latest tree-sitter toolchain. When used it errors with ` Incompatible language version. Compatible range: 13 - 13. Got: 11`. More context about what changed in tree-sitter can be found here: https://github.com/tree-sitter/tree-sitter/pull/943. Probably we just need to regenerate the `parser.c` and release new package.

**Comment by ikatyang** [comment]
I'll upgrade to the newest tree-sitter this weekend.

**Comment by char0n** [comment]
Thanks!
