### ISSUE TITLE
Trying to understand the Tree Sitter -- Missing Definitions Issue

### ISSUE THREAD

**Issue by jeff-hykin** [ikatyang/tree-sitter-yaml#46]
Given I didn't see a `$.comment` in the grammar.js, I did a global search, and shockingly found nothing.
Not only that but many other definitions like `$._bl` are also completely missing as far as I can tell, even after pulling the submodules to see if they were somehow hacked into the tree-sitter code itself.

Could one of the maintainers point me in the right direction for finding where these definitions are coming from?
I'm trying to learn how to handle indentation-based languages with the tree sitter.

**Comment by RedCMD** [comment]
https://github.com/tree-sitter/tree-sitter/blob/master/docs/section-3-creating-parsers.md#external-scanners
https://github.com/ikatyang/tree-sitter-yaml/blob/master/src/scanner.cc

**Comment by jeff-hykin** [comment]
Thanks @RedCMD ! I didn't know you did tree sitter stuff too
