### ISSUE TITLE
Extreme WASM size

### ISSUE THREAD

**Issue by char0n** [ikatyang/tree-sitter-yaml#5]
Hi @ikatyang,

First of all thank you for this YAML grammar for tree-sitter. I wanted to ask about the size of `src/parser.c` size. It seems a little bit extreme at 940K. After the parser grammar is compiled to WASM size is  719,3 KiB (736 604 bytes).

Are you aware of this? Can we do something about it?

Thanks!

**Comment by ikatyang** [comment]
Hi, I recompiled `tree-sitter-yaml.wasm` with `tree-sitter-cli@0.16.7`, it is now 135KB (b26d567).

**Comment by ikatyang** [comment]
The `parser.c` shipped with `npm:tree-sitter-yaml@0.1.0` is generated by `tree-sitter-cli@0.15.7`, you probably need to `tree-sitter generate` before `tree-sitter build-wasm` to get the 135KB wasm.

**Comment by char0n** [comment]
@ikatyang right, that decreased the size to expected 135KB WASM. Thanks
