### ISSUE TITLE
tree-sitter-cli compatibility

### ISSUE THREAD

**Issue by char0n** [ikatyang/tree-sitter-yaml#6]
Hi @Menci,

When we try to use [tree-sitter-cli@0.16.5](https://www.npmjs.com/package/tree-sitter-cli/v/0.16.5) to build this YAML grammar everything works great. The moment `tree-siter-cli` is updated to `>=0.16.6` the WASM compile successfully but when you try to run it in browser you'll get:

```
Couldn't find language function in WASM file. Symbols:
[
  "__post_instantiate",
  "dynCall_X",
  "dynCall_i",
  "dynCall_iii",
  "dynCall_iiii",
  "dynCall_vi",
  "dynCall_vii",
  "dynCall_viii"
]
```
It will be observable in your playground https://ikatyang.github.io/tree-sitter-yaml/ when you build this YAML grammar against latest [tree-sitter-cli@0.16.9](https://www.npmjs.com/package/tree-sitter-cli/v/0.16.9).

**Comment by ikatyang** [comment]
I did not get this error on the current playground, which is compiled using `tree-sitter-cli@0.16.7`, did I miss something? or is it a `tree-sitter-cli@0.16.9`-only issue?

**Comment by char0n** [comment]
Here the problem might be that I'm using latest [web-tree-sitter@0.16.4](https://www.npmjs.com/package/web-tree-sitter/v/0.16.4) but you're using web-tree-sitter@0.16.7 that you've build your self ?

**Comment by ikatyang** [comment]
- The `tree-sitter-yaml.wasm` produced by `tree-sitter-cli@0.16.7` is exact the same as the one produced by `tree-sitter-cli@0.16.9`.
- It works the same if I replace `docs/assets/web-tree-sitter-0.16.7` with `npm:web-tree-sitter@0.16.4`.
- Tested with Chrome, Firefox, and Safari on macOS.

**Comment by char0n** [comment]
The solution to our problem was to run`tree-sitter generate` before running `tree-sitter build-wasm`. Thanks for pointing me out to the right direction.
