### ISSUE TITLE
Support for Node 10.x.y

### ISSUE THREAD

**Issue by char0n** [ikatyang/tree-sitter-yaml#7]
Hi @ikatyang,

I've just noticed that the [grammar.js](https://github.com/ikatyang/tree-sitter-yaml/blob/master/grammar.js#L504) is using `Object.fromEntries` function which is not part of node 10. As node@10 is still in maintenance LTS, would be great if this YAML grammar supported it. 

Would you be open to replace `Object.fromEntries` and possibly other non node@10 functions to other implementations?

Thanks

**Comment by ikatyang** [comment]
Hi, the `grammar.js` is considered a dev-only file, which should only be used in Node 12+, though I didn't mention it anywhere. The `tree-sitter-yaml` npm package only guarantees that its node binding will work, which is the case for Node 10. If you'd like to use `grammar.js` in Node 10, I'd recommend you to use it via [`@babel/register`](https://babeljs.io/docs/en/babel-register.html) and/or [`@babel/polyfill`](https://babeljs.io/docs/en/babel-polyfill.html), for example:

```sh
NODE_OPTIONS='--require "path/to/babel-polyfill" --require "path/to/babel-register"' tree-sitter generate
```

or use Docker/nvm to achieve this goal.

**Comment by char0n** [comment]
Sure, thanks; fortunately I'm using babel and your proposed solution works. Might be problem for people without babel though. 

Thanks!
