### ISSUE TITLE
CST and literals

### ISSUE THREAD

**Issue by char0n** [ikatyang/tree-sitter-yaml#9]
Hi @ikatyang,

I was wondering if the CST that `tree-sitter-yaml` produces could additionally contain literals like `:`. 

Having a following yaml
```yaml
openapi: 3.1.0
``` 

I'd expect CST to contain the `:` literal as a SyntaxNode with a location information. Currently literals are consumed by the grammar. For example [tree-sitter-json](https://github.com/tree-sitter/tree-sitter-json) does provide literals as SyntaxNodes within CST. 

Thank you

**Comment by char0n** [comment]
@ikatyang not sure I see a difference in CST. What has actually changed ? Thanks!

**Comment by ikatyang** [comment]
They are now [anonymous nodes](https://tree-sitter.github.io/tree-sitter/using-parsers#named-vs-anonymous-nodes), and you can verify it by enabling "Query" in the playground:

![image](https://user-images.githubusercontent.com/8341033/94499522-7e437280-022f-11eb-8e33-b1203de2a7ab.png)

**Comment by char0n** [comment]
Hm interesting. This is what I see: 

![image](https://user-images.githubusercontent.com/193286/94534138-54467c00-0240-11eb-84ea-db85889993e8.png)

I've used `Incognito` Chrome window to eliminate any cache problems.

**Comment by char0n** [comment]
I do confirm that I'm seeing anonymous nodes when building [tree-sitter-yaml@0.2.0](https://www.npmjs.com/package/tree-sitter-yaml/v/0.2.0) locally. Great job!
